import { Router } from 'express';
import { prisma } from '../config/db';
import { authenticateToken, AuthenticatedRequest } from '../middlewares/authMiddleware';
import crypto from 'crypto';

const router = Router();

// GET /api/invitations - Get all active invitations generated by the landlord
router.get('/', authenticateToken, async (req: AuthenticatedRequest, res) => {
  try {
    const userId = req.user.id;
    if (req.user.role !== 'USER' && req.user.role !== 'ADMIN') {
      return res.status(403).json({ error: '권한이 없습니다.' });
    }

    const invitations = await prisma.invitation.findMany({
      where: { landlordId: userId },
      orderBy: { createdAt: 'desc' }
    });

    res.json(invitations);
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// POST /api/invitations - Generate a new invite code
router.post('/', authenticateToken, async (req: AuthenticatedRequest, res) => {
  try {
    const userId = req.user.id;
    if (req.user.role !== 'USER' && req.user.role !== 'ADMIN') {
      return res.status(403).json({ error: '권한이 없습니다.' });
    }
    
    let { tenantId } = req.body;
    if (!tenantId) tenantId = null;

    // Generate a secure random 8-character string
    const code = crypto.randomBytes(4).toString('hex').toUpperCase();

    const expiryDate = new Date();
    expiryDate.setDate(expiryDate.getDate() + 7); // Expires in 7 days

    const invitation = await prisma.invitation.create({
      data: {
        code,
        landlordId: userId,
        tenantId,
        expiresAt: expiryDate
      }
    });

    res.json(invitation);
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// DELETE /api/invitations/:id - Delete an invitation + 연동된 세입자 퇴실 처리
router.delete('/:id', authenticateToken, async (req: AuthenticatedRequest, res) => {
  try {
    const userId = req.user.id;
    const id = req.params.id as string;

    const invitation = await prisma.invitation.findUnique({ where: { id } });
    if (!invitation || invitation.landlordId !== userId) {
      return res.status(404).json({ error: '초대코드를 찾을 수 없습니다.' });
    }

    // --- 초대코드에 연결된 세입자 퇴실 처리 (트랜잭션) ---
    await prisma.$transaction(async (tx) => {
      // 1. 초대코드에 연결된 Tenant 레코드 조회
      let deactivatedUserIds: string[] = [];

      if (invitation.tenantId) {
        const tenant = await tx.tenant.findUnique({ where: { id: invitation.tenantId } });
        if (tenant?.loginUserId) {
          deactivatedUserIds.push(tenant.loginUserId);
        }
      }

      // 2. 초대코드를 사용하여 가입한 User 검색 (status ACTIVE인 TENANT 유저 중 해당 landlord 소속)
      // tenantId가 없는 경우에도 landlordId가 같고 role이 TENANT인 유저를 추가로 찾을 수 있음
      if (deactivatedUserIds.length === 0) {
        // fallback: invitation.code와 매칭되는 사용자가 있을 수 있으므로 스킵
      }

      // 3. 연결된 세입자 User 비활성화
      for (const tUserId of deactivatedUserIds) {
        await tx.user.update({
          where: { id: tUserId },
          data: {
            isActive: false,
            roomId: null,
            status: 'SUSPENDED'
          }
        });
      }

      // 4. 초대코드 삭제
      await tx.invitation.delete({ where: { id } });
    });

    res.json({ success: true, message: '초대코드가 삭제되고 연결된 세입자가 퇴실 처리되었습니다.' });
  } catch (e: any) {
    console.error('Invitation delete error:', e);
    res.status(500).json({ error: e.message });
  }
});

// GET /api/invitations/tenants - Get list of registered tenants for the landlord
router.get('/tenants', authenticateToken, async (req: AuthenticatedRequest, res) => {
  try {
    const userId = req.user.id;
    if (req.user.role !== 'USER' && req.user.role !== 'ADMIN') {
      return res.status(403).json({ error: '권한이 없습니다.' });
    }

    const tenantUsers = await prisma.user.findMany({
      where: { landlordId: userId, role: 'TENANT' },
      select: { id: true, username: true, status: true, createdAt: true }
    });

    res.json(tenantUsers);
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

// DELETE /api/invitations/tenants/:tenantId - Remove a tenant user
router.delete('/tenants/:tenantId', authenticateToken, async (req: AuthenticatedRequest, res) => {
  try {
    const userId = req.user.id;
    const tenantId = req.params.tenantId as string;

    const tenantUser = await prisma.user.findUnique({ where: { id: tenantId } });
    if (!tenantUser || tenantUser.landlordId !== userId || tenantUser.role !== 'TENANT') {
      return res.status(404).json({ error: '임차인 계정을 찾을 수 없습니다.' });
    }

    // Optionally handle cascading issues, but deleting User should be fine since MaintenanceRequests also point to it, which might restrict deletion if not standard cascade. 
    // We should just suspend them instead.
    await prisma.user.update({
      where: { id: tenantId },
      data: { status: 'SUSPENDED' }
    });
    
    res.json({ success: true });
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

export default router;
